version: "2.3"
services:
  bodypix:
    runtime: nvidia
    build:
      context: ./bodypix
      dockerfile: /home/charlescsr/vbkd/bodypix/Dockerfile
    image: bodypix
    restart: always
    ports:
      - 8000:8000
    command: node /src/app.js
    devices:
      - /dev/nvidia0:/dev/nvidia0
  fakecam:
    build:
      context: ./fakecam
      dockerfile: /home/charlescsr/vbkd/fakecam/Dockerfile
    image: fakecam
    restart: always
    links:
        - bodypix
    command: python fake.py
    environment:
      ACTUAL_CAMERA: "/dev/video0"
      FAKE_CAMERA: "/dev/video20"
      CAMERA_WIDTH: "640"
      CAMERA_HEIGHT: "360"
      #CAMERA_WIDTH: "1280"
      #CAMERA_HEIGHT: "720"
      CAMERA_FPS: "24"
      BODYPIX_URL: http://bodypix:8000
    volumes:
        - /home/charlescsr/vbkd/data:/data
    devices:
        - "/dev/video0:/dev/video0"
        - "/dev/video20:/dev/video20"
networks:
  fakecam:
    driver: bridge
